from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class AIAuditLog(models.Model):
    STATUS_CHOICES = (
        ("SUCCESS", "Success"),
        ("VALIDATION_FAILED", "Validation Failed"),
        ("EXECUTION_ERROR", "Execution Error"),
        ("SECURITY_BLOCK", "Security Block"),
    )

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name="ai_audit_logs")
    user_prompt = models.TextField(help_text="Original natural language query submitted by user")
    generated_sql = models.TextField(null=True, blank=True, help_text="SQL statement generated by AI engine")
    status = models.CharField(max_length=30, choices=STATUS_CHOICES, default="SUCCESS")
    execution_time_ms = models.FloatField(default=0.0, help_text="Query execution duration in milliseconds")
    tables_accessed = models.JSONField(default=list, help_text="List of database tables/collections accessed")
    row_count = models.IntegerField(default=0, help_text="Number of records returned")
    error_message = models.TextField(null=True, blank=True)
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "AI Audit Log"
        verbose_name_plural = "AI Audit Logs"

    def __str__(self):
        return f"[{self.status}] {self.user_prompt[:40]} ({self.created_at.strftime('%Y-%m-%d %H:%M')})"
