# Generated by Django 6.0.1 on 2026-10-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', max_length=10),
        ),
    ]
