# Generated by Django 6.0.1 on 2026-10-01 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_prompt",
                    models.TextField(
                        help_text="Original natural language query submitted by user"
                    ),
                ),
                (
                    "generated_sql",
                    models.TextField(
                        blank=True,
                        help_text="SQL statement generated by AI engine",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("VALIDATION_FAILED", "Validation Failed"),
                            ("EXECUTION_ERROR", "Execution Error"),
                            ("SECURITY_BLOCK", "Security Block"),
                        ],
                        default="SUCCESS",
                        max_length=30,
                    ),
                ),
                (
                    "execution_time_ms",
                    models.FloatField(
                        default=0.0,
                        help_text="Query execution duration in milliseconds",
                    ),
                ),
                (
                    "tables_accessed",
                    models.JSONField(
                        default=list,
                        help_text="List of database tables/collections accessed",
                    ),
                ),
                (
                    "row_count",
                    models.IntegerField(
                        default=0, help_text="Number of records returned"
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Audit Log",
                "verbose_name_plural": "AI Audit Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
