# Generated by Django 6.0.1 on 2026-10-01 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Data source display name",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "db_type",
                    models.CharField(
                        choices=[
                            ("MONGODB", "MongoDB (OlaCarsBackend ERP)"),
                            ("POSTGRESQL", "PostgreSQL"),
                            ("MYSQL", "MySQL"),
                            ("SQLITE", "SQLite"),
                        ],
                        default="MONGODB",
                        max_length=20,
                    ),
                ),
                ("host", models.CharField(blank=True, max_length=255, null=True)),
                ("port", models.IntegerField(blank=True, null=True)),
                ("database_name", models.CharField(max_length=100)),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Read-only user e.g. ola_ai_readonly",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MetricDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("REVENUE", "Revenue"),
                            ("BOOKINGS", "Bookings"),
                            ("FLEET", "Fleet"),
                            ("CUSTOMERS", "Customers"),
                            ("FINANCIAL", "Financial"),
                        ],
                        default="REVENUE",
                        max_length=50,
                    ),
                ),
                (
                    "sql_formula",
                    models.TextField(
                        help_text="Pre-validated SQL/MongoDB query formula for this metric"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TableMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_name",
                    models.CharField(
                        help_text="Exact collection or table name in database",
                        max_length=100,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Business explanation of what this entity represents",
                    ),
                ),
                ("is_sensitive", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="data_sources.datasource",
                    ),
                ),
            ],
            options={
                "unique_together": {("data_source", "table_name")},
            },
        ),
        migrations.CreateModel(
            name="ColumnMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_name", models.CharField(max_length=100)),
                ("data_type", models.CharField(max_length=50)),
                (
                    "business_meaning",
                    models.TextField(
                        blank=True,
                        help_text="Plain text description for AI query generator",
                    ),
                ),
                ("is_primary_key", models.BooleanField(default=False)),
                ("is_foreign_key", models.BooleanField(default=False)),
                (
                    "foreign_table",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="data_sources.tablemetadata",
                    ),
                ),
            ],
        ),
    ]
